### ISSUE TITLE
Not Connecting

### ISSUE THREAD

**Issue by kb3cat** [bitfocus/companion-module-tplink-kasasmartdimmer#2]
Since updating to 3.0.0, neither one of my switches will connect. I verified the IP addresses are correct, but neither switch will connect. Also added new connections to them, and did not work.

**Comment by josephdadams** [comment]
I am having trouble also. I will try to take another look at the code when I have time

**Comment by cpuguru07** [comment]
I am also having this issue since updating to 3.0.0.

**Comment by josephdadams** [comment]
I pushed a fix, v2.0.1 of the module. Please try that.

**Comment by ZacharyAiley** [comment]
Hello, I've purchased a new KS225 dimmer.  It's fully updated to version "1.1.1" but it's not connecting.  I am able to ping the device, but in the companion logs it's showing connection refused.  I'm curious if these devices have different firmware now, since it's fully updated to 1.1.1.
